workspace:
  base: /app
  path: src/github.com/high-value-team/featureforecast

pipeline:

  backend_build:
    image: library/mono
    commands:
      - mkdir -p /app/src/github.com/high-value-team/featureforecast/backend/bin/app
      - cp /app/src/github.com/high-value-team/featureforecast/backend/build/template.docker.Dockerfile /app/src/github.com/high-value-team/featureforecast/backend/bin/Dockerfile
      - cd /app/src/github.com/high-value-team/featureforecast/backend/src/featureforecast
      - nuget restore
      - msbuild /p:OutDir=/app/src/github.com/high-value-team/featureforecast/backend/bin/app featureforecast.sln

  backend_docker:
    debug: true
    image: plugins/docker
    repo: hvt1/featureforecast-backend
    secrets: [ docker_username, docker_password ]
    context: /app/src/github.com/high-value-team/featureforecast/backend/bin
    dockerfile: /app/src/github.com/high-value-team/featureforecast/backend/bin/Dockerfile

  frontend_build:
    image: node
    commands:
      - cd /app/src/github.com/high-value-team/featureforecast/frontend/build
      - yarn install
      - npx run build_for_drone

  frontend_docker:
    debug: true
    image: plugins/docker
    repo: hvt1/featureforecast-frontend
    secrets: [ docker_username, docker_password ]
    context: /app/src/github.com/high-value-team/featureforecast/frontend/bin
    dockerfile: /app/src/github.com/high-value-team/featureforecast/frontend/bin/Dockerfile

  frontend_rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: featureforecast/frontend
    docker_image: hvt1/featureforecast-frontend
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180

  backend_rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: featureforecast/backend
    docker_image: hvt1/featureforecast-backend
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180



